name: Update WordPress
on:
  schedule:
    - cron: '0 0 * * *' # Chạy lúc 0h UTC mỗi ngày
  workflow_dispatch: # Cho phép chạy thủ công
jobs:
  update-wordpress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Check WordPress version
        run: |
          LATEST_VERSION=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].current')
          echo "Latest WordPress version: $LATEST_VERSION"
          if [ -f "wordpress/wp-includes/version.php" ]; then
            CURRENT_VERSION=$(grep "wp_version = " wordpress/wp-includes/version.php | cut -d "'" -f 2)
            if [ "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
              echo "Already up-to-date with version $CURRENT_VERSION"
              exit 0
            fi
          fi
          echo "Downloading WordPress $LATEST_VERSION..."
          curl -L https://wordpress.org/wordpress-$LATEST_VERSION.zip -o latest.zip || { echo "Failed to download WordPress"; exit 1; }
          unzip latest.zip || { echo "Failed to unzip WordPress"; exit 1; }
          # Debug: Xem danh sách file/thư mục sau khi giải nén
          ls -la
          # Di chuyển thư mục wordpress từ bên trong wordpress-$LATEST_VERSION
          rm -rf wordpress
          mv wordpress-$LATEST_VERSION/wordpress wordpress || { echo "Error: wordpress directory not found inside wordpress-$LATEST_VERSION"; exit 1; }
          # Xóa thư mục wordpress-$LATEST_VERSION sau khi di chuyển
          rm -rf wordpress-$LATEST_VERSION
          # Tạo file wordpress.zip
          zip -r wordpress.zip wordpress || { echo "Failed to create wordpress.zip"; exit 1; }
          rm latest.zip
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update WordPress to $LATEST_VERSION" || echo "No changes to commit"
          git push
